// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnAqp2lnsrGOEjCvJTMYvW4hxeuMLgvWE',
    appId: '1:402078791499:web:0e22d9c4a8e9ccab86dace',
    messagingSenderId: '402078791499',
    projectId: 'the-barber-cd2a7',
    authDomain: 'the-barber-cd2a7.firebaseapp.com',
    storageBucket: 'the-barber-cd2a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCir1krRvkcemMV6nUbWjF_mqEcYTsyYYc',
    appId: '1:402078791499:android:08474e44152f417d86dace',
    messagingSenderId: '402078791499',
    projectId: 'the-barber-cd2a7',
    storageBucket: 'the-barber-cd2a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCGpyyWllfYc-sNwZO-PSy8Xin42diNE',
    appId: '1:402078791499:ios:9432af00fb6709a686dace',
    messagingSenderId: '402078791499',
    projectId: 'the-barber-cd2a7',
    storageBucket: 'the-barber-cd2a7.appspot.com',
    iosClientId: '402078791499-7h13q2kehaeeqqfenhg5kf097f8g3j4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBarber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCGpyyWllfYc-sNwZO-PSy8Xin42diNE',
    appId: '1:402078791499:ios:9432af00fb6709a686dace',
    messagingSenderId: '402078791499',
    projectId: 'the-barber-cd2a7',
    storageBucket: 'the-barber-cd2a7.appspot.com',
    iosClientId: '402078791499-7h13q2kehaeeqqfenhg5kf097f8g3j4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBarber',
  );
}
